# Generated by Django 2.1 on 2019-10-13 06:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mailinglist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriberMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sent', models.DateTimeField(default=None, null=True)),
                ('last_attempt', models.DateTimeField(default=None, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='mailinglist',
            name='id',
            field=models.UUIDField(default=uuid.UUID('09bbb53e-5981-4c54-aabe-36acdd8594e2'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.UUIDField(default=uuid.UUID('906f18c9-0765-44ed-83a6-69414a164cdd'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9c163fa1-bb24-4784-8cc4-a35df007c696'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='subscribermessage',
            name='message',
            field=models.ForeignKey(on_delete=mailape.db.models.deletion.CASCADE, to='mailinglist.Message'),
        ),
        migrations.AddField(
            model_name='subscribermessage',
            name='subscriber',
            field=models.ForeignKey(on_delete=mailape.db.models.deletion.CASCADE, to='mailinglist.Subscriber'),
        ),
    ]
